# This rule is not used by the project multicluster-role-assignment itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to rbac.open-cluster-management.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multicluster-role-assignment
    app.kubernetes.io/managed-by: kustomize
  name: multiclusterroleassignment-viewer-role
rules:
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - multiclusterroleassignments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - multiclusterroleassignments/status
  verbs:
  - get
