---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - multiclusterroleassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - multiclusterroleassignments/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - multiclusterroleassignments/status
  verbs:
  - get
  - patch
  - update
