apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: multicluster-role-assignment
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
