apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multicluster-role-assignment?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    # CEL expression for push builds - supports both main and release-2.16 branches
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "release-2.16"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: release-acm-216
    appstudio.openshift.io/component: multicluster-role-assignment-acm-216
    pipelines.appstudio.openshift.io/type: build
  name: multicluster-role-assignment-acm-216-on-push
  namespace: crt-redhat-acm-tenant
spec:
  params:
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: '{"type": "gomod", "path": "."}'
    - name: build-source-image
      value: "true"
    - name: git-url
      value: "{{source_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-role-assignment-acm-216:{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/ppc64le
        - linux/s390x
        - linux/arm64
    - name: dockerfile
      value: Dockerfile.rhtap
    - name: path-context
      value: .
    - name: send-slack-notification
      value: true
    - name: konflux-application-name
      value: release-acm-216
    - name: slack-member-id
      value: U0608EFFZB2 # @mshort, The slack member id of the current component owner.
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-multicluster-role-assignment-acm-216
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
